version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@8.2.1
  aws-ecs: circleci/aws-ecs@4.0.0

executors:
  ubuntu:
    working_directory: /tmp/work
    machine:
      image: ubuntu-2204:2024.04.4

jobs:
  parameters-check:
    docker:
      - image: cimg/python:3.9
    resource_class: small
    steps:
      - checkout
      - run:
          name: pipeline parameters check
          command: |
            echo "branch : ${CIRCLE_BRANCH}"
            echo "commit-hash : ${CIRCLE_SHA1}"

  build-and-push:
    executor: ubuntu
    parameters:
      repo:
        type: string
      dockerfile:
        type: string
        default: Dockerfile.prod
      extra_build_args:
        type: string
        default: ""
      path:
        type: string
        default: app/
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          checkout: false
          repo: << parameters.repo >>
          path: << parameters.path >>
          build-path: << parameters.path >>
          region: ap-northeast-1
          tag: ${CIRCLE_SHA1}
          dockerfile: << parameters.dockerfile >>
          extra-build-args: << parameters.extra_build_args >>
      - aws-ecr/tag-image:
          repo: << parameters.repo >>
          source-tag: ${CIRCLE_SHA1}
          target-tag: latest

workflows:
  deploy_main_to_ecs:
    jobs:
      - parameters-check:
          filters:
            branches:
              only:
                - main
      - build-and-push:
          repo: backend-service
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy_service_update:
          name: backend-service
          auth:
            - aws-cli/setup
          cluster: backend-cluster
          family: backend-task
          container_image_name_updates: "container=backend-app,tag=${CIRCLE_SHA1}"
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - main
