version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    ports:
      - "5002:5000"
    environment:
      FLASK_ENV: development
      DATABASE_URL: mysql+pymysql://root:password@db:3306/mydatabase
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flask-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
